FROM node:14-bullseye-slim AS node_build
WORKDIR /app
COPY package*.json ./
RUN npm ci --no-audit --no-fund
COPY resources ./resources
COPY public ./public
COPY webpack.mix.js ./
RUN npm run prod

FROM nginx:stable
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=node_build /app/public /var/www/public
